//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Input/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""Cube"",
            ""id"": ""9d59abdb-3fc0-4d77-b999-9d5c720cc969"",
            ""actions"": [
                {
                    ""name"": ""PointPress"",
                    ""type"": ""Value"",
                    ""id"": ""7c3cff19-52e6-4804-b59c-a6bf5bd1414d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0d06ad4d-6e16-47c2-aa88-a3138697c3b7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Cube
        m_Cube = asset.FindActionMap("Cube", throwIfNotFound: true);
        m_Cube_PointPress = m_Cube.FindAction("PointPress", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Cube
    private readonly InputActionMap m_Cube;
    private List<ICubeActions> m_CubeActionsCallbackInterfaces = new List<ICubeActions>();
    private readonly InputAction m_Cube_PointPress;
    public struct CubeActions
    {
        private @InputController m_Wrapper;
        public CubeActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @PointPress => m_Wrapper.m_Cube_PointPress;
        public InputActionMap Get() { return m_Wrapper.m_Cube; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CubeActions set) { return set.Get(); }
        public void AddCallbacks(ICubeActions instance)
        {
            if (instance == null || m_Wrapper.m_CubeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CubeActionsCallbackInterfaces.Add(instance);
            @PointPress.started += instance.OnPointPress;
            @PointPress.performed += instance.OnPointPress;
            @PointPress.canceled += instance.OnPointPress;
        }

        private void UnregisterCallbacks(ICubeActions instance)
        {
            @PointPress.started -= instance.OnPointPress;
            @PointPress.performed -= instance.OnPointPress;
            @PointPress.canceled -= instance.OnPointPress;
        }

        public void RemoveCallbacks(ICubeActions instance)
        {
            if (m_Wrapper.m_CubeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICubeActions instance)
        {
            foreach (var item in m_Wrapper.m_CubeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CubeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CubeActions @Cube => new CubeActions(this);
    public interface ICubeActions
    {
        void OnPointPress(InputAction.CallbackContext context);
    }
}
